[package]
name = "OSCARv2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rand = "0.9.2"
minifb = "0.24"
clap = { version = "4.0", features = ["derive"] }
